# Generated by Django 5.2.8 on 2025-11-10 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=255)),
                ("variacao", models.CharField(blank=True, max_length=255, null=True)),
                ("quantidade", models.IntegerField(default=0)),
                (
                    "preco",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("ultima_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoque_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "item", "variacao")},
            },
        ),
    ]
