# Generated by Django 5.2.8 on 2025-11-11 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_diariobordo"),
    ]

    operations = [
        migrations.CreateModel(
            name="RPD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                ("situacao", models.TextField()),
                ("pensamento_automatico", models.TextField()),
                ("emocao", models.CharField(max_length=255)),
                ("resposta_adaptativa", models.TextField()),
                ("resultado", models.TextField()),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rpd_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Pensamento Disfuncional",
                "verbose_name_plural": "Registros de Pensamentos Disfuncionais",
                "ordering": ["-data"],
            },
        ),
    ]
