# Generated by Django 5.2.8 on 2025-11-11 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rpd"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogPODDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateTimeField()),
                ("status", models.BooleanField(default=False)),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_pod_diario_entries",
                        to="api.atividade",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_pod_diario_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log POD Diário",
                "verbose_name_plural": "Logs POD Diários",
                "ordering": ["-data"],
            },
        ),
    ]
